/* words.js — 四级真题高频词库（2026-07-14 榜单 1367 词，按真题句频排序；"word|词性.释义"，取首个义项组便于游戏内显示） */
(() => {
const G = window.G = window.G || {};
const RAW = [
'would|aux. (will 的过去式)将要,会','author|n. 作者;作家; 创始人;发起者','researcher|n. 研究人员;调查者','less|det. 较少的;更少的(修饰不可数名词)','likely|adj. 很可能的;有希望的; 似乎合适的;看似可靠的',
'employee|n. 雇员,员工','accord|n. (国家、团体间的)协议; 一致;和谐','benefit|n. 好处;益处; 福利;救济金; 慈善活动;义演','system|n. 系统','effect|n. 影响;效果; 效果;印象; 个人物品;财产',
'local|adj. 当地的','actually|adv. 实际上,事实上(用于纠正或补充信息)','online|adj. 在线的;联网的; 网上的;线上的','better|adj. 更好的(good 的比较级)','tend|v. 倾向于,往往会',
'design|n. 设计;图案; 意图;目的; 设计学;设计艺术','product|n. 产品;商品; 产物;结果; 乘积','customer|n. 顾客,客户; (某种类型的)家伙,人','learning|n. 学习;学习过程; 学问;学识','career|n. 职业;事业; (终生的)经历;生涯',
'million|num. 一百万;百万','reduce|v. 减少,降低(数量、大小、程度等)','support|v. 支持','participant|n. 参与者;参加者','lack|v. 缺少;缺乏;没有',
'affect|v. 影响; 感动;打动(情感); 假装;装出','diet|n. 日常饮食; 节食;减肥餐; (某类)大量摄入的事物','relationship|n. 关系;联系; 恋爱关系;性关系; 关联;相关性','process|n. 过程;进程; 诉讼程序;传票','risk|n. 风险;危险; 危险人物;风险因素',
'focus|n. 重点','professor|n. 教授(大学教师的最高职称)','stress|n. 压力;紧张; 强调;重点; 重音; 应力;张力','financial|adj. 财政的;金融的;财务的','quality|n. 质量',
'decade|n. 十年','finding|n. 调查结果;研究发现; 裁决;判决; 发现物;找到的东西','impact|n. 影响;作用; 冲击;撞击','physical|adj. 身体的','type|n. 类型;种类; (某一类)人; 印刷字体;铅字',
'base|n. 基础;底部; 基地;总部; 基础;根据; 碱;盐基','behavior|n. 行为','project|n. 项目;工程; 专题作业;课题','simply|adv. 仅仅,只不过','average|adj. 平均的;普通的; 中等的(海损)',
'case|n. 情况','expert|n. 专家;行家','opportunity|n. 机会;时机','amount|n. 数量;金额','mental|adj. 精神的',
'view|n. 观点,看法; 景色,风景; 视野,视线; 观察,审视','consumer|n. 消费者','least|det. 最少的;最小的','access|n. 进入;使用权; 通道;入口; (疾病的)发作','issue|n. 问题',
'community|n. 社区','global|adj. 全球的','challenge|n. 挑战;艰巨任务; 质疑;异议','concern|v. 涉及;与……有关; 使担忧;使忧虑','individual|adj. 单独的;个别的; 独特的;与众不同的',
'traditional|adj. 传统的;惯例的; 守旧的;因循守旧的','rate|n. 速度;速率; 价格;费用; 等级;级别','sign|n. 标志;指示牌; 迹象;征兆; 手势;示意动作; 星座','factor|n. 因素;要素; 因子;因数; 系数;倍数','growth|n. 增长;增加; 生长;发育; 肿块;赘生物; 成长;发展',
'organization|n. 组织;机构; 组织;安排;筹备; 条理性;系统性','digital|adj. 数字的;数码的; 数字显示的; 手指的;指状的','contribute|v. 捐献','data|n. 数据;资料; (计算机)数据','decline|v. 下降;减少; 谢绝;婉拒; (语法)变格',
'major|adj. 主要的;重要的; 大调的','gender|n. 性别(社会文化意义上的)','later|adv. 以后,later;稍后','academic|adj. 学术的','material|n. 材料;原料; 资料;素材; 布料;织物',
'measure|v. 测量;衡量; 估量;判断','professional|adj. 专业的','department|n. 部门;系; (法国等国的)省; 专长;职责范围','event|n. 事件','performance|n. 表演',
'involve|v. 包含','current|adj. 现在的;当前的; 通用的;流通的','gain|v. 获得;赢得; 增加;增长; 到达;抵达','suffer|v. 遭受(痛苦、疾病、损失等)','effective|adj. 有效的,起作用的',
'potential|adj. 潜在的;可能的','pressure|n. 心理压力;精神负担; 压力;压强; 催促;敦促;施压','due|adj. 预期的;预定的; 应付的;到期的; 应得的;应有的','economic|adj. 经济的','positive|adj. 积极的',
'security|n. 安全','account|n. 账户; 叙述;描述;报告; 账目;账单; 重要性;价值','connection|n. 联系','policy|n. 政策;方针; 保险单;保单; 明智;策略;精明的做法','resident|n. 居民; 住院医生',
'climate|n. 气候; (社会、政治等的)氛围,风气,环境','device|n. 设备','option|n. 选择','power|n. 权力','apply|v. 申请',
'argue|v. 争论;争吵; 论证;主张;说理; 表明;证明;说明','economy|n. 经济;经济体系; 节约;节省','enable|v. 使能够','solve|v. 解决(问题、困难)','calorie|n. 卡路里,热量单位; 卡(物理学热量单位)',
'engage|v. 参与','negative|adj. 否定的','obesity|n. 肥胖(症)','claim|v. 声称;断言; 索取;认领; 夺去(生命)','reward|n. 报酬;奖励;回报; 好处;益处;收获',
'seek|v. 寻找;寻求; 征求;请求; 试图;力求; 追求;谋求','attack|v. 攻击','balance|n. 平衡;均衡; 余额;结余; 天平;秤; 制衡;平衡力量','creative|adj. 有创造力的','damage|n. 损害;损坏; 损害赔偿金; (对抽象事物的)伤害;损害',
'medium|adj. 中等的;中号的','responsibility|n. 责任;职责; 责任感;负责的态度; 责任归属;过失','ensure|v. 确保','identify|v. 识别','male|adj. 男性的;雄性的',
'resource|n. 资源','struggle|v. 奋斗;努力; 挣扎;搏斗; 艰难行进','wrong|adj. 错误的','generally|adv. 通常,一般地; 大体上,总的来说; 普遍地,广泛地','increasingly|adv. 越来越;日益;不断增加地',
'strategy|n. 策略;战略; 战略学;兵法','consume|v. 消耗,耗费(燃料、能源、时间等)','desire|n. 愿望;渴望; 情欲;性欲; 渴望的人(或物)','employer|n. 雇主;雇用者','evidence|n. 证据;证明; 迹象;痕迹',
'image|n. 形象,印象','link|n. 联系','perform|v. 执行','various|adj. 各种各样的;不同的; 若干的;数个的','determine|v. 决定',
'nation|n. 国家;民族国家; 民族;族群','protein|n. 蛋白质; (生物化学中的)蛋白质分子','species|n. 物种;种; 种类;类型','approach|v. 靠近,接近(在空间或时间上)','contain|v. 包含,含有',
'demand|v. 坚决要求;强烈请求; 需要;要求具备; 询问;质问','email|n. 电子邮件','emotional|adj. 情绪的','innovation|n. 创新;革新(指行为或过程); 新方法;新事物;创新成果','jam|n. 果酱; 交通堵塞; 困境',
'publish|v. 出版,发行(书籍、杂志等)','realize|v. 意识到,认识到','source|n. 来源;出处; 原始资料;文献; 源头;根源','per|prep. 每;每一; 依照;根据;按照; 通过;经由','shift|v. 移动',
'tax|n. 税;税款','available|adj. 可获得的','colleague|n. 同事','debate|n. 辩论;讨论','extra|adj. 额外的;附加的',
'intelligence|n. 智力;理解力; 情报;信息; 消息;资讯','recently|adv. 最近;近来','easily|adv. 容易地','official|adj. 官方的;正式的; 公开宣称的;公务的','promote|v. 促进',
'replace|v. 替换,更换(用新的代替旧的)','response|n. 回答','scientific|adj. 科学的;科学上的; 系统的;精确的','variety|n. 多样化;变化; 种类;品种; 综艺节目;杂耍表演','boost|v. 提高',
'exist|v. 存在','function|n. 功能;作用; 函数; 正式社交活动;宴会','loss|n. 丧失;失去; 亏损;损失; 损坏;损毁; 失败;战败','remove|v. 移开','associate|v. 联系;关联; 交往;结交; 使加入;使有联系',
'budget|n. 预算;经费','conduct|v. 组织并实施','detail|n. 细节;详情; (军队等的)小分队','educational|adj. 教育的;有关教育的; 有教育意义的;有启发性的','fashion|n. 时尚;流行款式; 方式;样子; 时装业;时尚界',
'limit|n. 限度;界限; (某地的)境界;范围; 极限;极点','media|n. 大众传播媒介(报刊、电视、广播、互联网等的总称)','region|n. 地区','consumption|n. 消费;消耗; 肺结核(旧称)','curiosity|n. 好奇心;求知欲; 稀奇古怪的东西;珍品; 稀罕事;怪事',
'figure|n. 数字; 人物; 身材;体形; 图形;图表; 轮廓;人影','generation|n. 一代人','harm|n. 伤害;损害','maintain|v. 维持','partner|n. 伴侣',
'trend|n. 趋势;倾向; 时尚;潮流','attend|v. 出席,参加(会议、活动等)','contact|n. 联系;接触; 触碰;接触; 联系人;熟人; 隐形眼镜','facility|n. 设施','firm|adj. 坚固的;结实的; 坚定的;坚决的; 明确的;确定的',
'reveal|v. 揭示','staff|n. 全体员工','adapt|v. 适应,适合(新环境、新情况)','charge|v. 收费','specific|adj. 具体的;特定的; 独特的;特有的',
'spot|n. 地点','teen|n. 青少年;十几岁的孩子','wild|adj. 野生的','adopt|v. 采纳','anxiety|n. 焦虑;忧虑; 焦虑症(医学); 渴望;急切的愿望',
'attract|v. 吸引(注意力、兴趣)','belief|n. 相信;信心; 信念;信仰; 看法;观点','billion|num. 十亿(1,000,000,000)','deliver|v. 递送,运送(货物、信件等)','failure|n. 失败; 失败的人或事; 故障;失灵; 未做;疏忽',
'further|adv. 更远地;在更远处; 进一步地;更深入地','management|n. 管理;经营; 管理层;管理人员; 管理学;管理专业','range|n. 范围','despite|prep. 尽管;虽然','explore|v. 探索',
'fund|n. 资金;基金; 储备;积累','importance|n. 重要性','interaction|n. 相互作用;互动; (物理、化学等的)相互作用','interested|adj. 感兴趣的;有兴趣的; 有利害关系的;有既得利益的','majority|n. 大多数,大部分',
'thinking|n. 思考;想法','vehicle|n. 交通工具;车辆; 媒介;手段;工具; 赋形剂;溶媒','writing|n. 写作','code|n. 代码;编码; 法规;法典;准则; 代号;编号','extreme|adj. 极度的',
'income|n. 收入;所得','item|n. 项目;条款; 新闻报道;消息; 一对;一双(恋人)','launch|v. 推出','overall|adj. 总体的;全面的','particularly|adv. 尤其,特别(强调某事物)',
'purchase|v. 购买','reflect|v. 反映,显示','status|n. 地位;身份; 状态;情形; 法律地位;法律身份','talent|n. 天赋','aim|v. 瞄准',
'concept|n. 概念;观念; (产品、设计等的)构想;设想','conflict|n. 冲突;矛盾; (心理上的)矛盾;内心冲突; 战斗;战争','consequence|n. 结果;后果; 重要性; 推论;推理','display|v. 展示;显示; 表现出(情感、品质)','district|n. 地区;区域',
'pollution|n. 污染; 污染物','reality|n. 现实','regular|adj. 经常的','smartphone|n. 智能手机','solution|n. 解决办法; 溶液; 答案;解答',
'teaching|n. 教学工作;教书; 教义;学说;教导','aging|n. 变老;老化','ban|v. 禁止;取缔','cash|n. 现金; 资金;财力','enhance|v. 提高;增强',
'feature|n. 特征','female|adj. 女性的;雌性的','particular|adj. 特定的','pattern|n. 模式;规律; 图案;花样; 样板;模板; 典范;榜样','previous|adj. 先前的;以前的; (时间上)过早的;仓促的',
'site|n. 地点;场所; 网站','snack|n. 零食;小吃; 容易办的事;轻而易举的事','user|n. 使用者;用户; 吸毒者','credit|n. 赊购,赊账','finally|adv. 终于,最终',
'flight|n. 航班','occur|v. 发生,出现; 存在于,出现于; 想到,浮现于脑海','rely|v. 依赖;依靠; 信赖;相信','significant|adj. 重要的;显著的; 有特殊意义的;意味深长的','essay|n. 短文;论文;文章',
'hire|v. 雇用;聘用; 租用;租借','indicate|v. 表明','interact|v. 相互作用;互动; (在社交场合)交往;交际','labor|n. 劳动;工作; 劳工;工人阶级; 分娩;生产','mostly|adv. 主要地;大部分; 通常;一般',
'personality|n. 个性','respond|v. 回答,答复','software|n. 软件(计算机程序)','unique|adj. 独特的','assume|v. 假定;认为; 承担;担任; 呈现;采取; 假装;装出',
'environmental|adj. 环境的;自然环境的; 周围环境的;外界环境的','expand|v. 扩大','expectation|n. 期待;预期; 预料;预测; 期望值;要求标准','graduate|n. 毕业生','lane|n. 车道',
'manufacturer|n. 制造商;生产厂家','muscle|n. 肌肉; 力量;影响力; 打手;保镖','recognize|v. 认出','recommend|v. 推荐','achievement|n. 成就;成绩; (成功的)完成;达到',
'crop|n. 农作物;庄稼; 收成;产量; 一批;一群','engineering|n. 工程学;工程技术; 策划;精心安排','household|n. 家庭;一家人','immigrant|n. 移民(从外国移入的人)','instance|n. 例子;实例; (计算机)实例; 要求;敦促',
'mission|n. 任务','motivate|v. 激励;激发; 成为...的动机;推动','rare|adj. 稀有的','reading|n. 阅读','track|n. 小路',
'agent|n. 代理人','ahead|adv. 在前面;向前; 领先;占优势; 提前;预先','authority|n. 权力','crisis|n. 危机;危急关头; (疾病的)转折期;危象','diversity|n. 多样性;差异性; 多样化的事物;各种各样的人或物',
'genetic|adj. 遗传的;基因的; 起源的;发生的','productive|adj. 富有成效的','protection|n. 保护','solar|adj. 太阳的;日光的; 利用太阳能的','advance|v. 前进;进展; 提出(观点、理论); 预付;提前支付',
'appeal|v. 呼吁;恳求; 吸引;引起兴趣; 上诉;申诉','cultivate|v. 培养,发展(技能、态度、关系等)','depression|n. 抑郁症','harmful|adj. 有害的;造成伤害的','outcome|n. 结果;结局',
'release|v. 释放;放开; 发布;发行; 排放;释放(物质)','saving|n. 节省;节约; 储蓄;存款(复数)','series|n. 系列;连续; 电视连续剧;广播连续节目; (数学)级数','style|n. 方式','theory|n. 理论;学说; 观点;见解; 理论知识;原理',
'tradition|n. 传统;惯例; 传统风格;传统派别','vary|v. 不同;有差异; (使)变化;改变; 使多样化;变换','application|n. 申请','assistant|n. 助手;助理; 虚拟助手;智能助理','aware|adj. 知道的;意识到的; 有…意识的;关注…的',
'characteristic|n. 特征;特点','critical|adj. 批评的','cultural|adj. 文化的;与文化相关的; 艺术文化的;文艺的','delay|n. 延迟;耽搁','differ|v. 不同,有区别; 持不同意见,意见不一致',
'electronic|adj. 电子的','essential|adj. 必不可少的;极其重要的; 本质的;基本的','executive|n. 主管;经理;管理人员; 行政部门;执行机构','means|n. 方法;手段; 财富;收入;财力','network|n. 网络;网状系统; 计算机网络; 广播电视网',
'panel|n. 专家小组','powerful|adj. 强大的','productivity|n. 生产率;生产力; 生产能力;创造力; 多产;富有成效','psychologist|n. 心理学家','recommendation|n. 推荐',
'remote|adj. 遥远的','retirement|n. 退休','stage|n. 阶段;时期; 舞台; 舞台;活动领域; 驿站;中转站','agency|n. 代理机构','argument|n. 争论',
'assignment|n. (学校的)作业、任务','being|n. 存在;生存; 生物;人','campaign|n. 运动;活动; 战役;军事行动; 竞选活动','chief|n. 首领;酋长;负责人; 老板;上司(非正式用语)','eventually|adv. 最终;终于; 可能;终究',
'grain|n. 谷物','improvement|n. 改进;改善; 改进之处;改良物; 康复;好转','journal|n. 杂志;期刊; 日记;日志; 日报; 日记账;分类账','opinion|n. 观点;看法;意见; 专家意见;鉴定; 舆论;民意','production|n. 生产',
'artificial|adj. 人造的','association|n. 协会','decrease|v. 减少,降低','earn|v. 赚得,挣得(金钱)','expense|n. 花费;费用; 代价;损失',
'familiar|adj. 熟悉的','fuel|n. 燃料; 刺激因素;推动力','gap|n. 间隙;缺口; 差距;差异; 空白期;间断; 缺口;不足','gas|n. 气体','handle|v. 处理',
'highly|adv. 非常;极其; 高度地;居高位地; 赞赏地;赞许地','mobile|adj. 可移动的','movement|n. 移动','payment|n. 支付;付款; 报酬;酬金; 报答;回报','represent|v. 代表',
'self|n. 自我;自身; 同色;单色','threat|n. 威胁;恐吓; 危险;隐患; 凶兆;征兆','understanding|n. 理解;领悟; 谅解;体谅; 协议;共识','valuable|adj. 贵重的;值钱的; 宝贵的;有用的','vision|n. 视力',
'app|n. 应用程序; 应用程序(泛指)','brand|n. 品牌,商标; 类型,种类','council|n. 委员会','distance|n. 距离;间距; 疏远;冷淡; 远处;远方','estimate|v. 估计;估算; 评价;评估',
'formula|n. 公式','gene|n. 基因','necessarily|adv. 必然地','satisfaction|n. 满意','aid|n. 帮助;援助; 辅助工具;辅助设备',
'audience|n. 观众;听众; 读者群;受众; 接见;拜见;谒见','competitive|adj. 竞争的','complex|adj. 复杂的,难懂的','diabetes|n. 糖尿病','ignore|v. 忽视',
'innovative|adj. 创新的;革新的; 富有创新精神的;善于革新的','principle|n. 原则,准则; 原理,定律; 行为准则,信条','quit|v. 离开(工作、学校等)','request|n. 请求;要求; 点播的歌曲; (计算机)请求;访问请求','thus|adv. 因此,所以; 以此方式,如此; 到如此程度',
'addition|n. 增加','beginning|n. 开始;起初; 起源;开端; 开头部分;前面部分','classical|adj. 古典的','content|n. 内容;所含之物; 含量;成分','corn|n. 玉米; 谷物;谷粒; 鸡眼; 陈词滥调;老套的东西',
'craft|n. 手艺;工艺; 行业;职业; 船只;飞行器; 狡猾;诡计','curriculum|n. 课程;全部课程','definitely|adv. 肯定地;确定地; 明确地;清楚地','educator|n. 教育工作者;教师; 教育家;教育理论家','establish|v. 建立,创立(组织、机构、关系等)',
'indeed|adv. 确实,的确(强调肯定)','instinct|n. 本能;天性; 直觉;天分','lower|adj. 较低的;下方的; 较少的;较小的','microwave|n. 微波炉; 微波','pain|n. 疼痛;痛苦; 精神痛苦;悲痛; 讨厌的人或事;麻烦',
'participate|v. 参加;参与','poverty|n. 贫穷;贫困; 缺乏;贫乏(指某种品质或要素的匮乏)','psychological|adj. 心理的','responsible|adj. 负责的','senior|adj. 级别高的;资深的; 年长的;年纪较大的',
'skin|n. 皮肤','soda|n. 苏打水','symptom|n. 症状;征兆; 征兆;迹象(指问题或不良情况的表现)','tip|n. 小费; 尖端;末端; 建议;提示;窍门; 垃圾场','warning|n. 警告;告诫; 警示;先兆; 警告处分;告诫通知',
'yeah|intj. 是的','acquire|v. 获得','analysis|n. 分析;分析结果; 心理分析;精神分析','announce|v. 宣布','attempt|v. 试图;尝试',
'block|n. 街区','central|adj. 主要的','container|n. 容器','define|v. 给……下定义','designer|n. 设计师; 阴谋策划者;图谋不轨的人',
'economist|n. 经济学家','federal|adj. 联邦(制)的; 联邦制拥护的','former|adj. 以前的,从前的','fossil|n. 化石; 化石燃料; 老古董;思想陈旧的人','largely|adv. 主要地;在很大程度上; 大量地;大规模地',
'meaningful|adj. 有意义的','platform|n. 平台','possibility|n. 可能性','rent|v. 租用','reverse|v. 颠倒;使反向',
'shortage|n. 短缺;不足','strengthen|v. 加强','survive|v. 幸存','target|n. 目标;靶子; 目标受众;目标群体; 靶场;射击场','technological|adj. 技术的;科技的; 工艺的;技术工艺方面的',
'transfer|v. 转移;调动; 转让;让与; 转接(电话)','trap|n. 陷阱','update|v. 更新;使现代化; 向…提供最新信息','workforce|n. (一国或一地区的)劳动力,劳动人口','awareness|n. 意识;认识; 觉察力;警觉',
'carrot|n. 胡萝卜','cell|n. 细胞','chain|n. 链条','character|n. 性格','combine|v. (使)结合、组合; 兼有、兼备(特性)',
'commercial|adj. 商业的','concerned|adj. 担心的;忧虑的; 关心的;关切的; 涉及的;有关的','confidence|n. 信心','confirm|v. 证实','currently|adv. 目前,当前',
'cycle|n. 循环;周期; 自行车;摩托车','delivery|n. 递送','disaster|n. 灾难;灾祸; 彻底的失败;一团糟','dolphin|n. 海豚; 鲯鳅(一种食用鱼)','foundation|n. 基础',
'grand|adj. 宏伟的','guide|n. 指南;手册; 导游;向导; 指导原则;准则','happiness|n. 幸福;快乐; (某事带来的)愉快;满意','highway|n. 公路;干道; 捷径;途径','legal|adj. 法律的',
'limited|adj. 有限的','massive|adj. 巨大的,大量的','priority|n. 优先事项','reader|n. 读者','relative|n. 亲戚,亲属',
'rescue|v. 营救,救援','routine|n. 常规','ultimately|adv. 最终;终归; 根本上;从根本上说','vulnerable|adj. 易受伤害的','additional|adj. 额外的;附加的',
'applicant|n. 申请人;求职者','aspect|n. 方面;层面; 外观;外貌; (动词的)体; 方位;朝向','beauty|n. 美','collapse|v. 倒塌,坍塌','contrast|n. 对比;差异',
'crime|n. 犯罪行为; 犯罪活动(总称); 罪过;不道德的事','criticism|n. 批评;指责; 评论;评论文章; 批评的话;批评意见','crowd|n. 人群; 一伙人;一帮人','crucial|adj. 至关重要的;关键性的; 决定性的;紧要关头的','curious|adj. 好奇的',
'flexible|adj. 灵活的','gather|v. 聚集,集合','gradually|adv. 逐渐地,逐步地','institution|n. 机构','invest|v. 投资(金钱、时间等以期获得回报)',
'location|n. 地点,位置; 外景拍摄地; 定位,定点','luxury|n. 奢侈品;奢华享受; 难得的乐事;享受的机会','native|adj. 本国的','political|adj. 政治的','relevant|adj. 相关的;有关的; 有价值的;有意义的',
'retire|v. 退休','stuff|n. 东西;物品; 特质;本质;素质; 废话;胡说','willing|adj. 愿意的,乐意的; 自愿的,主动的','yield|v. 产生;出产; 让步;屈服; 让路;让行; 弯曲;塌陷','affordable|adj. 买得起的',
'basis|n. 基础;根据; 方式;原则; 要素;主要成分','bean|n. 豆,豆子','behave|v. 表现,举止','collection|n. 收集物','comment|n. 评论;意见; 注释;批注; 议论;评说',
'construction|n. 建造','cope|v. 应对;处理(困难局面); 对付;应付(无 with)','county|n. 郡;县','disappear|v. 消失;不见; 失踪;下落不明; 灭绝;绝迹','discount|n. 折扣;减价',
'enormous|adj. 巨大的;庞大的; 极大的(用于强调严重性或重要性)','fixed|adj. 固定的','formal|adj. 正式的','habitat|n. (动植物的)栖息地,生长环境; (人的)居住地,聚居地','institute|n. 学院;研究所',
'intake|n. 摄入量','investigate|v. 调查;研究; 调查(某人)','multiple|adj. 多个的;多种的','nutrition|n. 营养;营养学','observe|v. 观察',
'ordinary|adj. 普通的;平常的; 平庸的;毫无特色的','parental|adj. 父母的;亲代的','perceive|v. 理解,领悟(某事的性质或意义)','quantity|n. 数量;量; 大量; (数学、物理中的)量','refugee|n. 难民;避难者',
'salary|n. 薪水,工资(通常指按月发放的固定报酬)','schedule|n. 时间表;日程安排; 清单;一览表; (美)课程表','slightly|adv. 稍微,略微,轻微地; 身材瘦削地,纤细地','vote|n. 投票;选票; 表决结果;票数','wallet|n. 钱包;皮夹; (数字货币)钱包;电子钱包',
'worldwide|adj. 全世界的;世界范围的','academy|n. 学院','admit|v. 承认(事实、错误等)','advocate|v. 拥护;提倡;主张','ambitious|adj. 有雄心的',
'assign|v. 分配(任务、工作)','award|n. 奖;奖品; (法院的)裁定额;赔偿金','bone|n. 骨','burger|n. 汉堡包; 肉饼','campus|n. (大学或学院的)校园; (大型机构的)园区,场地',
'capable|adj. 有能力的','carbon|n. 碳(化学元素)','complicated|adj. 复杂的;难懂的; (情况、关系)复杂的;棘手的','contribution|n. 贡献','criminal|n. 罪犯;犯人',
'deeply|adv. 深深地','document|n. 文件;文档','efficiency|n. 效率','expose|v. 使暴露','extend|v. 延伸',
'fee|n. 费用;服务费','grant|v. 授予;准许; 承认;同意(某事属实)','ideal|adj. 理想的;完美的; 理想化的;不切实际的','inspire|v. 激励','investment|n. 投资',
'journey|n. 旅行,旅程; 历程,过程','locate|v. 找到','military|adj. 军事的;军队的; 军人般的;纪律严明的','peer|n. 同龄人;同辈; 贵族;有贵族头衔的人','portion|n. 部分;一份; (食物的)一份; 命运;命中注定的事',
'pose|v. 摆姿势(供拍照或绘画)','preserve|v. 保护','profit|n. 利润,盈利; 好处,益处','propose|v. 提议','reserve|v. 预订;保留; 保留(权利、意见等)',
'scale|n. 规模','signal|n. 信号;暗号; 标志;征兆','sink|v. 下沉','strength|n. 力量','structure|n. 结构',
'tough|adj. 困难的','transport|v. 运输,运送; 使心驰神往,使沉醉','vast|adj. 巨大的;广阔的','widespread|adj. 广泛的;普遍的','alternative|n. 可供选择的事物;替代方案',
'amazing|adj. 令人惊奇的;了不起的; 令人惊讶的;难以置信的','annual|adj. 每年的,年度的; 全年的,一年的','apart|adv. 分开地','citizen|n. 公民;国民; 市民;居民','clearly|adv. 清楚地,明白地; 显然,明显地; 无疑地,确实地',
'complain|v. 抱怨;投诉; 诉说(病痛)','elderly|adj. 年老的;上了年纪的','emphasis|n. 强调;重点; 加强语气;重读','entire|adj. 整个的;全部的; 完全的;彻底的(用于强调)','favor|n. 帮忙;恩惠; 支持;赞同; 小礼物;纪念品',
'feedback|n. 反馈','funding|n. 资金;经费','generate|v. 产生,引起(结果、反应等)','grocery|n. 食品杂货; 食品杂货店','hinder|v. 阻碍,妨碍',
'hunger|n. 饥饿; 渴望;渴求','initiative|n. 主动性','judge|v. 判断,评判; 批评,指责','mayor|n. 市长','meanwhile|adv. 与此同时;在此期间; 其间;在那段时间里',
'minor|adj. 较小的;次要的; 小调的','motivation|n. 动力;积极性; 动机;原因','narrow|adj. 狭窄的','novel|n. 小说','parking|n. 停车;停车位',
'penalty|n. 处罚;惩罚; 不利后果;代价; 点球;罚球','perception|n. 看法;认识; 感知;知觉; 洞察力;领悟; 察觉;注意','property|n. 财产;资产; 房地产;不动产; 特性;性质; 道具','romantic|adj. 浪漫的','roughly|adv. 大约,大概; 粗暴地,粗鲁地; 粗略地,简略地',
'truly|adv. 真正地','urban|adj. 城市的,都市的; 城市文化的,街头风格的','vital|adj. 极其重要的,必不可少的','wisdom|n. 智慧;明智; (某一领域的)知识体系;学问','actual|adj. 真实的;实际的; (用于强调)真正的',
'adjust|v. 调整','advanced|adj. 先进的;高级的; 晚期的;后期的; 超前的;前卫的','analytical|adj. 善于分析的','appearance|n. 外貌;外观; 出现;露面; 到来;出现; 假象;表象','bar|n. 酒吧',
'burden|n. 负担','capacity|n. 容量','combat|n. 战斗;搏斗; 格斗;搏击','commitment|n. 承诺','compete|v. 竞争;对抗; 参赛;参加比赛',
'conventional|adj. 传统的','corporate|adj. 公司的;企业的; 共同的;集体的; 法人的;社团的','critic|n. 批评家;评论家; 批评者;反对者','ease|n. 容易;轻松; 舒适;安逸','emerge|v. 出现',
'error|n. 错误;失误; 过失;罪过; 误差','evil|adj. 邪恶的','graduation|n. 毕业;毕业典礼; 刻度;分度; 逐步进展;渐变','honor|n. 荣誉;名誉; 荣幸;光荣; 荣誉称号;奖励','identity|n. 身份',
'implication|n. 可能的影响或结果; 含意、暗示; 牵连、涉及','imply|v. 暗示,暗指; 必然包含,意味着; 表明,说明','incident|n. (尤指不寻常或令人不快的)事件,事情','ingredient|n. (烹饪)食材,原料; (抽象)要素,因素','injury|n. (身体)伤害,损伤',
'intelligent|adj. 聪明的;智力高的; 智能的(指机器、系统等)','leadership|n. 领导地位','loneliness|n. 孤独感;寂寞; 偏僻;荒凉','nap|n. 小睡,打盹; 绒毛,绒面; (纸牌游戏)拿破仑','numerous|adj. 众多的,许多的',
'okay|adj. 可以的;还行的; 安全的;健康的','opera|n. 歌剧; 歌剧院;歌剧团','physician|n. 医生;内科医生','popularity|n. 受欢迎;流行; 普及度;广泛使用','promotion|n. 晋升,升职; 促销,推广活动; 促进,推动',
'pub|n. 酒吧;酒馆','recall|v. 回忆起,记起; 召回(产品、人员等); 使想起,使忆起','recession|n. 经济衰退','remind|v. 提醒;使想起; 使联想到;使记起(人或事物)','requirement|n. 要求;必要条件; 需要;需求',
'setting|n. 环境','severe|adj. 严重的','spouse|n. 配偶','studio|n. 工作室','technique|n. 技术;技巧; 技艺;手法(艺术、体育等领域)',
'tobacco|n. 烟草;烟叶; 烟草业;烟草行业','transform|v. 使彻底改变;使转变; (数学)使变换;使转换','transportation|n. 交通运输(系统)','trash|n. 垃圾;废物; 劣质的东西;垃圾作品','waiter|n. (餐厅的)服务员,侍者',
'worried|adj. 担心的;忧虑的','acknowledge|v. 承认(事实、错误等)','aircraft|n. 飞行器;航空器','alert|adj. 警觉的;机敏的','border|n. 边界;国界; 边缘;边',
'chef|n. 厨师长;主厨; 烹饪大师;名厨','clothing|n. 衣服;服装(总称); 覆盖物;遮盖层','commit|v. 承诺、保证做某事','concentrate|v. 集中注意力; 集中(于某地); 浓缩','context|n. (事情发生的)背景、环境',
'counterpart|n. 对应的人或物','crash|v. (车辆)猛撞,碰撞','emergency|n. 紧急情况,突发事件','emission|n. 排放物','evolve|v. 逐渐发展',
'helicopter|n. 直升机','host|n. 主人','immune|adj. 有免疫力的;不受影响的; 免除的;豁免的','listener|n. 听者;听众; 善于倾听的人; 监听者;窃听者','mass|n. 大量;许多; 团;块;堆; 群众;民众; 质量; 弥撒',
'mood|n. 心情','nowadays|adv. 现在;当今;如今','player|n. 运动员','poisonous|adj. 有毒的','pursue|v. 追求',
'regardless|adv. 不管;无论如何','rival|n. 竞争对手;对手','settle|v. 解决(争端、问题)','shock|n. 震惊','strive|v. 努力,奋斗,力求; 斗争,抗争',
'suit|n. 套装;西装; 诉讼;起诉; (扑克牌的)花色','valley|n. 山谷;溪谷; 流域; 低谷期;困难时期','victim|n. 受害者','abandon|v. 离弃','absorb|v. 吸收(液体、气体等)',
'challenging|adj. 有挑战性的;考验能力的; 质疑的;挑战权威的','circumstance|n. 情况','court|n. 法院','definition|n. 定义;释义; 清晰度;鲜明度; 界限;轮廓','demonstrate|v. 证明',
'division|n. 分开','donation|n. 捐赠;捐款; (器官、血液等的)捐献','eliminate|v. 消除','elsewhere|adv. 在别处;到别处','employment|n. 工作;职业; 雇佣;聘用(行为); 使用;利用',
'era|n. 时代;年代','following|adj. 接下来的;其后的','frequent|adj. 频繁的;经常发生的','guideline|n. 指导方针;准则','homeless|adj. 无家可归的',
'immediate|adj. 立即的,即刻的','intervention|n. 干预;介入; 调停;斡旋; (医疗)治疗措施;手术','involved|adj. 参与的','loan|n. 贷款;借款; 借出(物);出借; 借用球员;租借球员','marketing|n. 营销;市场营销',
'missing|adj. 找不到的;失踪的; 缺少的;不存在的','mom|n. 妈妈','mule|n. 骡子(马和驴的杂交后代)','nightmare|n. 可怕的经历;梦魇般的情境; 噩梦; 令人头疼的人或事物','obvious|adj. 明显的;显而易见的',
'organize|v. 组织,安排(活动、会议等)','passion|n. 强烈的情感','press|v. 按,压; 催促,逼迫; 熨烫; 坚持,强调','prospect|n. 可能性;前景; 潜在客户;有前途的人; 景象;景色','pump|n. 泵;抽水机',
'register|v. 登记,注册','regulation|n. 规则,条例; 管理,控制','respondent|n. 被告;答辩人; 调查对象;受访者','rid|v. 使摆脱;使去除','stable|adj. 稳定的;稳固的',
'sustainable|adj. 可持续的','switch|v. 转换;改变; 交换;调换; 突然转移(注意力、话题等)','tendency|n. 倾向;趋势; (政治、思想的)倾向;派别','therapy|n. 治疗','therefore|adv. 因此,所以',
'tourism|n. 旅游业;观光业; 游客流量;旅游活动','wage|n. 工资;薪水','wander|v. 漫步','wildlife|n. 野生动植物','yoga|n. 瑜伽',
'absence|n. 缺席;不在; 缺乏;不存在; 心不在焉','abstract|adj. 抽象的','accomplishment|n. 成就;成绩; 才能;技能; 完成;实现','accurate|adj. 准确的;精确的; (武器、投掷等)精准的','analyze|v. 分析',
'attraction|n. 吸引力','attractive|adj. 有吸引力的','attribute|n. 属性;特征','beneficial|adj. 有益的;有利的','bias|n. 偏见;偏向; 斜纹;斜裁; 偏压;偏置电压',
'certainly|adv. 当然','charity|n. 慈善机构','combination|n. 结合','comfort|n. 舒适','debt|n. 欠款;债务; 人情债;恩情',
'distinguish|v. 区分','divorce|n. 离婚; 分离,脱离','eager|adj. 热切的;渴望的; 热心的;积极的','efficient|adj. 效率高的;能干的; (机器、系统)性能好的','emphasize|v. 强调;着重; 使突出;加强(语气、效果等)',
'engine|n. 发动机,引擎','fancy|v. 想要','flavor|n. 味道','imitate|v. 模仿','intend|v. 打算,计划; 意指,意思是; 想要给予,打算给予',
'junk|n. 废物','learner|n. 学习者;学员; (英国)学习驾驶的人;驾驶学员','medal|n. 奖章;勋章','moral|adj. 道德的','myth|n. 神话',
'operate|v. 运转','pace|n. 速度;步伐; 步;一步的距离','percentage|n. 百分比,百分率; 提成,回扣; 好处,利益','perspective|n. 观点','persuade|v. 说服;劝说; 使相信;使信服',
'possibly|adv. 可能,也许','puzzle|n. 谜;智力游戏; 难题;令人费解的事','reduction|n. 减少','regarding|prep. 关于;至于','scene|n. 场景',
'sector|n. (经济或商业的)部门,行业','secure|adj. 安全的','select|v. 选择,挑选','sensitive|adj. 敏感的','setback|n. 挫折;倒退; (建筑物的)缩进部分',
'socialize|v. 社交','spending|n. 开支;花费;支出','statement|n. 声明','stock|n. 库存','submit|v. 提交(文件、申请等)',
'sufficient|adj. 足够的;充足的','typical|adj. 典型的','wireless|adj. 无线的','wooden|adj. 木制的,木头的','accomplish|v. 完成,实现(任务、目标)',
'analyst|n. 分析师;分析者; 心理分析师;精神分析师','anxious|adj. 焦虑的','approval|n. 赞成;同意; 批准;许可; (商品)试用期;试用销售','assess|v. 评估;评定; 估定(税额、罚款等); 征收(税款)','assistance|n. 帮助;援助; (社会福利性质的)补助;救济',
'astronaut|n. 宇航员;航天员','atmosphere|n. 气氛;氛围; 大气层;大气; 空气;气体; 情调;格调','beer|n. 啤酒; 一杯(或一瓶、一罐)啤酒','blame|v. 责备;归咎于','calm|adj. 平静的;镇定的',
'candidate|n. 候选人;应试者; 适合人选;合适的事物; 攻读学位者','consideration|n. 考虑','contract|n. 合同','creature|n. 生物','deserve|v. 应得;值得; 应受(用于客气地提出请求或建议)',
'destination|n. 目的地;终点; 目标;目的','detect|v. 发现,察觉(难以察觉的事物); 侦查,侦破(犯罪活动)','diverse|adj. 多种多样的;不同的; 形形色色的;各不相同的','donate|v. 捐赠,捐献(金钱、物品等); 捐献(器官、血液等)','encounter|v. 遇到;遭遇(尤指困难或问题)',
'exciting|adj. 令人兴奋的;激动人心的','farming|n. 农业;耕作; (游戏中的)刷材料;重复获取资源','governor|n. 州长','guarantee|n. 保证;担保; 担保人;保证金','hunt|v. 搜寻;寻找; 打猎;猎取',
'implement|v. 实施;执行;使生效','indicator|n. 指示物','inspiration|n. 灵感','investigation|n. 调查;侦查; 研究;探究','label|n. 标签',
'lecture|n. 讲座;演讲; 训斥;教训','load|n. 负载;装载的货物; 工作量;负担; 大量;许多(口语)','naturally|adv. 自然地','neighborhood|n. 街区;社区; 邻近;附近; 邻里关系;友好往来','norm|n. 常态;规范;标准; (数学)范数; 定额;标准量',
'obviously|adv. 显然,明显地; (用于强调陈述)当然,无疑','odd|adj. 奇怪的','pearl|n. 珍珠; 珍贵的人或物;精华; 珍珠色;珍珠般的光泽','persuasion|n. 说服;劝说; 信念;信仰; 派别;宗派','pursuit|n. 追求;寻求; 追赶;追捕; 消遣;爱好',
'rank|n. 等级;级别; 行列;队列','rarely|adv. 很少,难得,不常','rating|n. 等级','reluctant|adj. 不情愿的;勉强的','royal|adj. 王室的',
'running|n. 跑步(运动); 运转,运行;管理','sample|n. 样品;样本','schooling|n. 学校教育; 训练;培养','shrink|v. 缩小;收缩; 退缩;畏缩','silicon|n. 硅(化学元素)',
'specifically|adv. 明确地','statistic|n. 统计数字;统计资料','stimulate|v. 刺激','sunlight|n. 日光;阳光','superior|adj. 更好的',
'tablet|n. 药片','tap|v. 轻敲、轻拍; 开发利用(资源); 窃听(电话等)','theme|n. 主题','tuition|n. 学费; 教学;讲授;指导','unemployed|adj. 失业的;待业的',
'urge|v. 敦促;力劝; 驱策;驱赶; 极力主张;竭力推荐','urgent|adj. 紧急的,急迫的; 急切的,迫切的(指愿望、请求等)','accessible|adj. 可到达的','adulthood|n. 成年期','ambition|n. 雄心;志向; 追求的目标;抱负',
'apartment|n. 公寓;单元房; (大型住宅的)一套房间','assumption|n. 假定','attach|v. 贴上','barely|adv. 几乎不;勉强; 仅仅;只是; 光秃秃地;赤裸裸地','chat|v. 聊天,闲谈',
'chemical|adj. 化学的','client|n. 客户','competitor|n. 竞争者;对手; 参赛者','costly|adj. 昂贵的,代价高的; 造成重大损失的,代价惨重的','crew|n. 全体船员',
'criticize|v. 批评','defense|n. 防御','distraction|n. 分心','domestic|adj. 国内的','drawing|n. 图画;素描; 绘画(技艺); 抽签;抽奖',
'economics|n. 经济学; 经济状况;经济因素','employ|v. 雇用; 使用、运用(方法、技能等); 花费(时间)','enjoyable|adj. 令人愉快的;使人快乐的','escape|v. 逃跑','estate|n. 地产',
'expression|n. 表达','extraordinary|adj. 非凡的','facilitate|v. 促进;使便利; 主持(会议、讨论)','fellow|n. 家伙','flexibility|n. 灵活性',
'freedom|n. 自由','guy|n. 男人','imagination|n. 想象力','import|v. 进口;输入; 导入(数据、文件)','infection|n. 传染',
'keen|adj. 热衷的','mix|v. 混合;搅拌; 交往;相处; 混音;调音; 混淆;搞混','mystery|n. 神秘的事物','nutrient|n. 营养物质;营养素','oppose|v. 反对;阻挠; 与…对抗;与…竞争; 使对立;使对比',
'optimistic|adj. 乐观的;抱乐观态度的; 过于乐观的;高估的','overseas|adv. 在海外;向海外','phenomenon|n. 现象;事件; 奇才;非凡的人(或物)','planning|n. 规划;计划(过程); 城市规划;规划许可','plus|prep. 加,加上; 外加;另有',
'preference|n. 偏爱','preparation|n. 准备','primarily|adv. 主要地;首要地; 最初;起初','proposal|n. 提议;建议; 求婚; (研究、项目等的)申请书','recover|v. 恢复健康',
'recycle|v. 回收利用(废品)','reputation|n. 名声;名誉; 名气;声望','root|n. 根;根部; 根源;起源; 根基;基础','route|n. 路线;路径; 途径;方法','scholar|n. 学者;专家; 奖学金获得者; 好学的人;勤奋学习者',
'secondary|adj. 次要的','session|n. 会议','shoot|v. 射击','suddenly|adv. 突然地;忽然','suspect|v. 怀疑;猜想',
'thrive|v. 茁壮成长;兴旺发达; 以……为乐;因……而兴旺','trace|v. 追踪;查找; 描绘;勾画; 追溯;概述','uniform|n. 制服;校服','vegetarian|n. 素食者','wave|n. 波浪',
'web|n. 网站','whereas|sc. 然而;而(表示对比); 鉴于;考虑到(法律文件用语)','witness|n. 目击者;证人; 证据;证明','accumulate|v. 积累','adequate|adj. 足够的,充分的; 胜任的,合格的',
'appropriate|adj. 合适的;恰当的','approve|v. 批准,认可(正式同意)','assessment|n. 评估;评价; 测评;考核; 估价;估定的金额','athlete|n. 运动员','automatic|adj. 自动的',
'badly|adv. 严重地;非常; 拙劣地;差劲地; 不利地;糟糕地','bite|v. 咬; 叮、蜇; 产生不良影响、起作用; 上钩','bond|n. 纽带','boom|n. 繁荣;激增; 隆隆声;轰鸣声','bubble|n. 泡;气泡; 泡沫;假象; 泡泡;隔离圈',
'cage|n. 笼子; 护栏;防护罩; 击球练习场','celebration|n. 庆祝活动; 庆祝;赞美','cite|v. 引用,引证; 传唤,传讯; 表彰,嘉奖; 举例说明','compromise|n. 妥协;折中方案','concrete|n. 混凝土',
'confusion|n. 困惑;糊涂; 混乱;乱成一团; 混淆;混同','constant|adj. 持续不断的','convey|v. 传达、表达(信息、思想、感情等)','creation|n. 创造','cure|v. 治愈(疾病); 解决(问题); 腌制(食物)',
'depth|n. 深度','dietary|adj. 饮食的;膳食的','discipline|n. 纪律;自律; 学科;专业领域','disorder|n. 疾病;失调; 混乱;骚乱','dramatic|adj. 巨大的',
'drought|n. 干旱;旱灾; 缺乏;匮乏(比喻用法)','exact|adj. 精确的;准确的; 严谨的;一丝不苟的','exposure|n. 暴露','flood|n. 洪水;水灾; 大量;泛滥','flow|v. 流动',
'found|v. find 的过去式和过去分词','freshman|n. (大学或高中)一年级新生; 新手;初学者','garbage|n. 垃圾;废物; 废话;无价值的东西; 废弃食物;厨余','heritage|n. 遗产;传统; 继承物;遗产(个人或家族); 血统;出身','highlight|n. 最精彩的部分',
'impression|n. 印象','incentive|n. 激励;刺激因素','infrastructure|n. 基础设施; (信息技术)基础架构','initial|adj. 最初的;开始的','inner|adj. 内部的,里面的',
'insight|n. 洞察力;深刻理解; 见解;领悟; 自知之明;病识感','instant|n. 瞬间,刹那','instructor|n. 教练;指导员; (大学)讲师; 教官;培训师','investor|n. 投资者;投资机构','kindergarten|n. 幼儿园',
'longevity|n. 长寿;寿命长; 持久性;持续时间长','modest|adj. 谦虚的,谦逊的','obese|adj. 肥胖的;过度肥胖的','ongoing|adj. 持续进行的;正在发生的; 不断发展的;持续性的','overcome|v. 克服',
'overlook|v. 忽略,没注意到; 俯瞰,眺望; 宽恕,不予追究','procedure|n. 程序','prompt|v. 促使;激起; 提示;提醒','raw|adj. 未加工的','react|v. 作出反应',
'reliable|adj. 可靠的;可信赖的; (信息、数据等)准确可靠的','revenue|n. (公司、组织的)收入,收益','semester|n. 学期(尤指大学的半学年)','skilled|adj. 熟练的;有技能的; 需要技能的;技术性的','spokesperson|n. 发言人;代言人',
'stretch|v. 伸展','strike|v. 打击','tackle|v. 处理','threaten|v. 威胁','union|n. 工会',
'youth|n. 青年时期','zone|n. 区域;地带; (体育运动中的)区域防守;联防','administration|n. 管理','agriculture|n. 农业;农学','alarm|n. 警报器;闹钟; 恐慌;惊恐',
'alter|v. 改变,更改(使某物与之前不同)','architect|n. 建筑师; 缔造者;设计师;策划者','arrangement|n. 安排;筹备; 协议;约定; 排列;布置; 改编曲','artistic|adj. 艺术的;有艺术性的; 有艺术天赋的;爱好艺术的','assist|v. 帮助;协助',
'attachment|n. 附件(邮件或文档的)','battery|n. 电池','beverage|n. 饮料','bonus|n. 奖金,红利','calculate|v. 计算',
'casual|adj. 随意的','chase|v. 追赶,追逐; 追求,寻求(目标、梦想等); 催促,催讨','cholesterol|n. 胆固醇','collaborate|v. 合作;协作; 通敌;勾结','complaint|n. 抱怨',
'consensus|n. (意见的)一致','consultant|n. 顾问;咨询师; (医院的)专科医生;会诊医师','continent|n. 大陆;洲','decorate|v. 装饰;装修; 授勋;颁奖表彰; 粉刷;涂漆(房屋内部)','deny|v. 否认; 拒绝给予; 克制,节制(自己的欲望)',
'dependent|adj. 依靠的;依赖的; 取决于……的;由……决定的','derive|v. 获得;得到; 源自;起源于; 推导;演绎','description|n. 描述;描写;叙述; 类型;种类','discourage|v. 使泄气;使灰心; 劝阻;阻止; 妨碍;阻碍','discrimination|n. 歧视; 辨别力;鉴赏力; 区别对待;差别',
'embrace|v. 拥抱; 欣然接受;乐意采纳; 包含;包括','explanation|n. 解释;说明; 辩解;辩护理由','exploration|n. 探索;勘探; 探究;研究; 探查;检查(医学)','finance|n. 财政;金融;资金; 财务状况;资金来源','folk|n. 人们;大家; 家人;亲属; 民族;部族',
'fortune|n. 财富','giant|adj. 巨大的;特大的','hunting|n. 打猎;狩猎; 寻找;搜寻','infant|n. 婴儿;幼儿; 未成年人(法律用语)','interior|n. 内部;内部空间; 内陆;内地',
'interpret|v. 解释;理解; 口译;翻译; 演绎;诠释(艺术作品)','isolation|n. 隔离;孤立; 单独考虑;孤立看待; 隔离措施;隔离期','justice|n. 公正;正义; 司法制度;法律制裁; 法官','kilometer|n. 千米,公里','layer|n. 层',
'lightning|n. 闪电','melt|v. (使)融化,熔化','membership|n. 会员资格','mess|n. 脏乱','minister|n. 部长;大臣; 牧师;神职人员; 公使;外交使节',
'motor|n. 发动机;马达','negotiate|v. 谈判','negotiation|n. 谈判;协商; (障碍、困难等的)成功越过;顺利通过','objective|n. 目标;目的; 物镜(显微镜或望远镜的)','obstacle|n. 障碍物;阻碍',
'opening|n. 开口','opponent|n. 对手;敌手; 反对者;反对派','opt|v. 选择;决定','otherwise|adv. 否则,不然','outdoor|adj. 户外的,室外的; 喜爱户外活动的,适合户外的',
'permanent|adj. 永久的;长期的','precious|adj. 珍贵的','presence|n. 在场','proverb|n. 谚语;格言','psychology|n. 心理学; 心理;心理特征; 心理影响;心理战术',
'radical|adj. 根本的;彻底的; 激进的;极端的','rational|adj. 理性的','reaction|n. 反应','reap|v. 获得,得到(回报、好处或后果); 收割,收获(庄稼)','reasonable|adj. 合理的',
'reform|v. 改革;改进(制度、法律等); 改造;使改过自新','relieve|v. 减轻、缓解(疼痛、焦虑等不适)','remarkable|adj. 非凡的;卓越的; 值得注意的;显著的','resolve|v. 解决(问题、困难)','seemingly|adv. 看似,似乎(表面上看起来是这样,但实际可能并非如此)',
'shade|n. 阴凉处','shelter|n. 遮蔽处;避难所; 住所;居所; 庇护;保护','shuttle|n. 往返于两地间的交通工具(飞机、火车、公共汽车等)','sponsor|n. 赞助商','strain|n. 压力',
'surgery|n. 外科手术','surround|v. 围绕','trial|n. 审判,审讯; 试验,试用; 考验,磨难; 预赛,选拔赛','trick|n. 诡计','undertake|v. 承担',
'unemployment|n. 失业(状态); 失业率;失业人数','virtual|adj. 虚拟的(计算机生成的)','vitamin|n. 维生素','wealthy|adj. 富有的;富裕的','welfare|n. 福利;幸福; 社会福利;救济金; 福利事业;福利工作',
'alike|adj. 相似的;相像的','ancestor|n. 祖先,祖宗; 原型,前身','arise|v. 出现','blog|n. 博客,网络日志','breed|v. 繁殖;培育; 引起;造成',
'bride|n. 新娘','category|n. 类别;种类','cereal|n. 谷物(早餐); 谷类植物;谷物','ceremony|n. 典礼;仪式; 礼节;客套; (宗教或传统的)仪式行为','certificate|n. 证书;证明书',
'clinical|adj. 临床的','commission|n. 佣金','component|n. 组成部分;成分','concentration|n. 专注;专心; 集中;聚集; 浓度','concerning|prep. 关于;有关',
'conservation|n. 保护','contest|n. 比赛;竞赛; 争夺;竞争','contrary|adj. 相反的;对立的; 执拗的;爱唱反调的','convenient|adj. 方便的','convince|v. 说服,使相信; 使确信,使信服(自己)',
'deadly|adj. 致命的','deficiency|n. 缺乏;不足; 缺陷;缺点','devote|v. 把…奉献给;致力于; (在宗教或正式场合)献祭;供奉','dioxide|n. 二氧化物','distribute|v. 分发;分配; 分布;散布; 配送;经销; 分摊;分担',
'element|n. 要素','emit|v. 发出,排放(光、热、气体等)','endless|adj. 无尽的','entertainment|n. 娱乐活动;娱乐节目; 款待;招待','ethnic|adj. 种族的;民族的; 具有异国风情的;民族风格的',
'exchange|n. 交换','existing|adj. 现有的;现存的','fairly|adv. 相当','fame|n. 名声;名望','fundamental|adj. 基本的;根本的;基础的',
'furthermore|adv. 此外;而且','halt|v. 停止;中止','harmony|n. 和谐;融洽; 和声;和谐悦耳的组合; 协调一致;匀称','illustrate|v. 说明;阐明; (给书籍、文章等)配图; 表明;证实','impose|v. 强制实行',
'incredibly|adv. 极其,非常(表示程度)','induce|v. 诱导','industrial|adj. 工业的','inform|v. 告知,通知(正式地告诉某人某事)','injure|v. 使受伤; 损害(名誉、感情等)',
'intense|adj. 强烈的','knit|v. 编织(用毛线等); (使)紧密结合;愈合; 皱(眉)','leisure|n. 闲暇;空闲时间','lunar|adj. 月球的;月亮的; 按阴历的;按月相的','lung|n. 肺',
'manner|n. 方式','marine|adj. 海洋的;海生的; 航海的;海运的','mechanism|n. 机制','mere|adj. 仅仅的;只不过的','monthly|adj. 每月的;按月的',
'necessity|n. 必需品','normally|adv. 通常;正常情况下; 正常地;正常方式','outer|adj. 外部的,外面的','outlet|n. 商店','panic|n. 恐慌;惊慌',
'passive|adj. 被动的','peak|n. 山峰;顶点; 顶峰;最高点;高峰期; 帽舌;帽檐','perfection|n. 完美;完善; 完美的人或事物; 完善;改进到完美的过程','philosopher|n. 哲学家; 善于思考人生的人;达观的人','politician|n. 政治家;政客',
'poll|n. 民意调查','practical|adj. 实际的','profession|n. 职业(尤指需要专门技能和培训的)','profitable|adj. 盈利的,有利可图的; 有益的,有用的','proportion|n. 部分;份额; 比例;比率; 规模;程度',
'recruit|v. 招募','reject|v. 拒绝接受','relief|n. 宽慰','renewable|adj. 可再生的;可更新的; 可续期的;可延长的','retain|v. 保留',
'rider|n. 骑马者','saying|n. 谚语;格言','scar|n. 伤疤','sharp|adj. 锋利的,尖锐的','sophisticated|adj. 复杂精密的',
'span|n. 时间段;期间; 跨距;跨度','spark|n. 火花; 一点点;微量','sum|n. 总数;总额; 算术题; 要点;概要','sustain|v. 维持','systematic|adj. 系统的;有条理的; 蓄意的;成体系的(尤指坏事)',
'thief|n. 小偷;窃贼','timely|adj. 及时的;适时的','tissue|n. 纸巾; (生物)组织; 薄纸;棉纸; 一系列;一连串','undergo|v. 经历,经受(尤指艰难、痛苦或变化的过程)','universal|adj. 普遍的',
'upper|adj. 上面的,上层的','version|n. 版本','acceptable|adj. 可接受的;令人满意的; (社会上)可接受的;得体的','addiction|n. 上瘾;沉溺; 热衷;入迷','adventure|n. 冒险经历;奇遇; 冒险精神;刺激; 投机活动;商业冒险',
'advertising|n. 广告业;广告活动','aisle|n. (建筑物内的)过道,通道; (教堂的)侧廊','apologize|v. 道歉;认错; 辩解;辩护','apparent|adj. 显而易见的,明显的','apparently|adv. 显然,看来(根据外表或所见所闻判断)',
'arouse|v. 激起,引起(情感、反应)','arrange|v. 安排,筹备(活动、会议等)','asset|n. 资产;有价值的人或物; 有用或有价值的人或事物;优点','automatically|adv. 自动地; 不假思索地;机械地; 必然地;当然地','bundle|n. 捆;束;包; 一大笔钱; 软件包;捆绑包',
'cafe|n. 咖啡馆;小餐馆','capability|n. 能力','cigarette|n. 香烟,纸烟','civilization|n. 文明(社会)','classify|v. 将…分类;把…归类; 将…列为机密;把…定为保密',
'collaboration|n. 合作;协作; 合作成果;协作作品; 通敌;勾结(贬义)','considerable|adj. 相当大的;相当多的','convert|v. 转变','crowded|adj. 拥挤的,挤满人的; (日程、生活)繁忙的,排满的','dislike|v. 不喜欢;厌恶',
'dispute|n. 争论;纠纷','distinction|n. 区别','distribution|n. 分配','dull|adj. 无聊的','educate|v. 教育',
'entertaining|adj. 有趣的;使人愉快的','excess|n. 过量;超出部分; 放纵;无节制的行为','exhibit|v. 展览','expectancy|n. 预期寿命;预期存续期; 预期;期待','export|v. 出口,输出(商品到国外)',
'extent|n. 程度;范围; (土地的)面积;广度','fade|v. 逐渐消失','fare|n. 车费;票价; 饭菜;食物; 乘客','file|n. 文件;档案; 锉刀; 纵列;行列','frequency|n. 频率',
'genius|n. 天才','gratitude|n. 感激;感恩','historical|adj. 历史的','independence|n. 独立','index|n. 索引;目录; 指数;指标; 食指; 标志;迹象',
'integrate|v. 使融入','intention|n. 意图','interfere|v. 干涉,介入(他人事务)','kindness|n. 善良;仁慈(品质); 善行;好意(具体行为)','laptop|n. 笔记本电脑',
'literacy|n. 读写能力; (某领域的)知识,素养','literature|n. 文学','logical|adj. 符合逻辑的','mall|n. 购物中心; 林荫大道;步行街','mammal|n. 哺乳动物',
'maximize|v. 使最大化;充分利用; (计算机)最大化窗口','misunderstanding|n. 误解;误会; 争执;不和','narrative|n. 叙述;讲述; 叙事体;记叙文','net|n. 网;网状物; 互联网;网络','obtain|v. 获得;得到; 存在;流行;通行',
'occupy|v. 占据,占用(空间、时间)','original|adj. 最初的,原始的; 原创的,独创的','outstanding|adj. 杰出的,出色的','oven|n. 烤箱;烤炉; (比喻)酷热的地方;闷热环境','overwhelming|adj. 压倒性的;巨大的; 难以承受的;令人不知所措的',
'passionate|adj. 热情的;热烈的; 激情的;情欲的; 易怒的;暴躁的','philosophy|n. 哲学','pile|n. 堆;摞; 大量;许多; 桩;柱; 绒面;绒毛; 痔疮','principal|adj. 主要的;最重要的','prior|adj. 先前的,之前的; 更重要的,优先的',
'privacy|n. 隐私;私密; 独处;清静','promising|adj. 有希望的;有前途的','realistic|adj. 现实的','recovery|n. 恢复','relate|v. 使有联系,把…联系起来',
'representative|n. 代表;代理人; (美国)众议院议员','resemble|v. 像;类似','restriction|n. 限制;约束; 限制性事物;受限状态','retail|n. 零售;零售业','revolution|n. 革命;彻底变革; 旋转;公转; 循环;周期',
'ruin|v. 毁坏;破坏; 使破产;使倾家荡产','scholarship|n. 奖学金; 学问;学术成就; 学者身份;学者群体','slip|v. 滑倒','somewhat|adv. 有点;稍微;在某种程度上','specialist|n. 专家;专科医生',
'split|v. 分开;分离; 分享;分摊; 离开;匆忙离去','string|n. 线,细绳; 一串,一系列; 字符串(计算机)','supporter|n. 支持者;拥护者; 赞助者;资助者; 支撑物;托架','tasty|adj. 美味的,可口的; 吸引人的,有趣的(非正式)','tear|v. 撕裂,撕破; 疾驰,飞奔',
'temporary|adj. 暂时的;临时的','timing|n. 时机选择;时间安排; 计时;定时; 节奏;节拍','tone|n. 语气,口气','trigger|v. 引发;触发','undergraduate|n. 大学本科生',
'vigorous|adj. 充满活力的','violence|n. 暴力行为; 激烈、猛烈; 歪曲、违背','virus|n. 病毒(引起疾病的微生物)','visual|adj. 视觉的;看得见的; 视觉化的;图像的;形象的','vocabulary|n. 词汇量;词汇; 词汇表;术语表; 表达方式;表达手段',
'weaken|v. 使变弱','acquaintance|n. 相识的人,熟人','adjustment|n. 调整','administrative|adj. 行政的;管理的; 行政部门的;政府管理的','advancement|n. 进步;发展; 晋升;提升; 预付款;预支',
'advertise|v. 为…做广告','advisor|n. 顾问;指导老师; (研究生的)导师','aged|adj. 年老的','aggressive|adj. 好斗的','agricultural|adj. 农业的;农艺的',
'anger|n. 愤怒;生气','anticipate|v. 预料,预期(某事将发生)','authentic|adj. 真实的;真正的; 可靠的;可信的; 地道的;正宗的','bacteria|n. 细菌','barrier|n. 障碍物;屏障; 障碍;阻碍(抽象); 界限;分界线',
'belong|v. 属于(某人)','bold|adj. 勇敢的,大胆的','bother|v. 打扰;烦扰; 费心;花费精力','branch|n. 树枝','brick|n. 砖,砖块; 砖形物;块状物; (非正式)好人;可靠的人',
'bury|v. 埋葬,安葬','castle|n. 城堡; (国际象棋中的)车','characterize|v. 是…的特征','cloth|n. 布料','clue|n. 线索;迹象; (纵横字谜等的)提示;谜面; 了解;知晓',
'compensate|v. 补偿;赔偿; 抵消;弥补(缺陷); (心理上)过度补偿','confuse|v. 使困惑;使糊涂; 混淆;搞混; 使复杂化;使混乱','constitute|v. 构成,组成; 被视为,相当于; 设立,成立','contaminate|v. 污染;弄脏; 玷污;损害(抽象事物); 传染;感染','continuous|adj. 连续不断的;持续的; 连绵的;绵延不绝的(指空间)',
'cooperate|v. 合作;配合; 协助;配合(尤指配合调查或遵守规定)','corporation|n. 公司,企业(尤指大型的、有限责任的)','crack|v. 破裂','cruise|v. 乘船游览','cyclist|n. 骑自行车的人',
'deed|n. 行为;行动; 契约;房地产证书','deteriorate|v. 恶化,变坏; (使)腐烂,变质','donkey|n. 驴; 蠢人;固执的人','earthquake|n. 地震; 剧变;大动荡','engagement|n. 约定',
'excessive|adj. 过多的;过度的','exhaust|v. 使筋疲力尽; 用尽,耗尽; 详尽讨论,彻底探讨','fabric|n. 织物;布料; 结构;构造; 织物类型;面料种类','faculty|n. (大学的)系,院','feasible|adj. 可行的;行得通的; (理论、解释等)似乎合理的',
'founder|n. 创始人;创办者; 铸造工;翻砂工','frame|n. 框架','frustration|n. 挫败感;沮丧; 受挫;阻挠; 令人沮丧的事物','genuine|adj. 真的','grab|v. 抓住;夺取; 匆忙取得;赶紧吃(喝); 吸引(注意力)',
'grateful|adj. 感激的','greenhouse|n. 温室;暖房','harvest|n. 收获;收成; 收获量;收获物; 成果;后果','hearing|n. 听力','humanity|n. 人类(总称); 人性;人道;仁慈; 人文学科',
'incredible|adj. 极好的','irregular|adj. 不规则的','kilogram|n. 千克,公斤(重量单位,等于1000克)','landscape|n. 风景;景色; 形势;格局;态势','liquid|n. 液体',
'manual|adj. 手工的;用手操作的; 体力的;需用力的','manufacture|v. (大规模)制造,生产; 编造,捏造(虚假信息)','merely|adv. 仅仅,只不过; 不过是,无非是(表轻视)','minority|n. 少数','moderate|adj. 适度的;中等的; 温和的;稳健的(政治观点)',
'neutral|adj. 中立的','occasion|n. 场合;时刻; 理由;原因','origin|n. 起源;由来; 出身;血统; 原产地;产地','overwhelm|v. 使不知所措','painful|adj. 疼痛的',
'patience|n. 耐心;忍耐力; 单人纸牌游戏','pension|n. 养老金;退休金; (欧洲的)小旅馆;家庭旅馆','persistent|adj. 坚持不懈的','phrase|n. 短语;词组; 说法;表达方式; 乐句;乐节','possession|n. 拥有',
'precisely|adv. 精确地,准确地','prescribe|v. 开(药)','prospective|adj. 预期的','qualify|v. 使具备资格','quantitative|adj. 定量的;数量的',
'readily|adv. 乐意地','recognition|n. 认可;赞赏; 识别;辨认; 承认;认可(地位、权利等)','remedy|n. 治疗方法','renovate|v. 翻新;修复(建筑物等); 革新;更新(系统、组织等)','repeatedly|adv. 反复地;多次地',
'risky|adj. 有风险的;危险的','roast|v. 烤,烘烤(肉类或蔬菜)','rural|adj. 乡村的,农村的','sex|n. 性别; 性行为;性交; 性欲;性吸引力','spacecraft|n. 航天器;宇宙飞船',
'stressful|adj. 压力大的;紧张的','stroke|n. 中风','substance|n. 物质','substitute|n. 替代品;代替者;替补','subway|n. 地铁; 地下通道; 赛百味(快餐连锁店)',
'sunshine|n. 阳光,日光','super|adj. 极好的,超级棒的','symbol|n. 象征;标志; 符号;记号; 代表人物;典型','tremendous|adj. 巨大的','villager|n. 村民',
'volume|n. 音量','willpower|n. 意志力;自制力'
];
function parse(rows) {
  const out = [];
  for (const row of rows) {
    const bar = row.indexOf('|');
    out.push({ w: row.slice(0, bar).toLowerCase(), zh: row.slice(bar + 1) });
  }
  return out;
}
function shuffle(a) { for (let i = a.length - 1; i > 0; i--) { const j = (Math.random() * (i + 1)) | 0; [a[i], a[j]] = [a[j], a[i]]; } return a; }
// Focus on a common, unambiguous meaning instead of overwhelming beginners with rare senses.
const MORE = [
['eager','adj. 渴望的','She is eager to learn.'],
['earn','v. 挣得','He works to earn a living.'],
['effort','n. 努力','Learning takes time and effort.'],
['electric','adj. 电的','An electric train passes the station.'],
['embrace','v. 拥抱；欣然接受','Embrace a new beginning.'],
['emerge','v. 出现','The sun emerges from the clouds.'],
['emotion','n. 情绪','Music can express emotion.'],
['encourage','v. 鼓励','Small wins encourage me to continue.'],
['energy','n. 能量；精力','A short walk gives me energy.'],
['enormous','adj. 巨大的','The city has an enormous station.'],
['entire','adj. 整个的','We spent the entire day together.'],
['environment','n. 环境','Keep the environment clean.'],
['escape','v. 逃离','We escaped from the noise.'],
['essential','adj. 必不可少的','Water is essential for life.'],
['event','n. 事件；活动','The next event starts at noon.'],
['evidence','n. 证据','We need more evidence.'],
['explore','v. 探索','Explore the city on foot.'],
['familiar','adj. 熟悉的','This street looks familiar.'],
['fancy','v. 想要；喜爱','I fancy a cup of tea.'],
['feature','n. 特点','The garden is a special feature.'],
['flexible','adj. 灵活的','My schedule is flexible.'],
['focus','v. 集中注意力','Focus on one word at a time.'],
['fortune','n. 运气；财富','Good fortune brought us together.'],
['frequent','adj. 频繁的','There are frequent trains to the city.'],
['generous','adj. 慷慨的','That was a generous gift.'],
['gentle','adj. 温和的','A gentle breeze moves the leaves.'],
['glance','v. 瞥一眼','Glance at the map before you go.'],
['grateful','adj. 感激的','I am grateful for your help.'],
['habit','n. 习惯','Reading is a daily habit.'],
['hesitate','v. 犹豫','Do not hesitate to ask for help.'],
['honest','adj. 诚实的','Give me an honest answer.'],
['imagine','v. 想象','Imagine walking through the stars.'],
['improve','v. 改善；提高','Practice helps me improve.'],
['include','v. 包括','The price includes breakfast.'],
['independent','adj. 独立的','She is an independent thinker.'],
['inspire','v. 激励','Your story inspires me.'],
['journey','n. 旅程','Every journey starts with a step.'],
['judge','v. 判断','Do not judge a book by its cover.'],
['knowledge','n. 知识','Books are a source of knowledge.'],
['landscape','n. 风景','Rain changes the landscape.'],
['leisure','n. 闲暇','I read in my leisure time.'],
['likely','adj. 可能的','It is likely to rain tonight.'],
['local','adj. 当地的','Visit a local bookshop.'],
['maintain','v. 维持','Maintain a steady pace.'],
['memory','n. 记忆','This song brings back a happy memory.'],
['mild','adj. 温和的','The weather is mild today.'],
['moment','n. 片刻','Enjoy this quiet moment.'],
['narrow','adj. 狭窄的','We walked down a narrow street.'],
['notice','v. 注意到','Did you notice the little cafe?'],
['observe','v. 观察','Observe the lights on the water.'],
['opportunity','n. 机会','This is an opportunity to learn.'],
['ordinary','adj. 普通的','It was an ordinary day.'],
['patient','adj. 耐心的','Be patient with yourself.'],
['peaceful','adj. 平静的','The park is peaceful at night.'],
['perhaps','adv. 也许','Perhaps we will meet again.'],
['pleasant','adj. 令人愉快的','Have a pleasant evening.'],
['prefer','v. 更喜欢','I prefer walking to driving.'],
['prepare','v. 准备','Prepare for a new adventure.'],
['protect','v. 保护','An umbrella protects you from rain.'],
['purpose','n. 目的','What is the purpose of this trip?'],
['quality','n. 质量','Quality matters more than quantity.'],
['quiet','adj. 安静的','The street is quiet after midnight.'],
['recognize','v. 认出','I recognize that familiar voice.'],
['reflect','v. 反射；认真思考','The windows reflect the streetlights.'],
['relax','v. 放松','Take a breath and relax.'],
['remind','v. 提醒','Remind me to bring an umbrella.'],
['repeat','v. 重复','Could you repeat that word?'],
['require','v. 需要','Good work requires patience.'],
['respect','v. 尊重','Respect other people.'],
['reward','n. 奖励','A warm drink is my reward.'],
['rhythm','n. 节奏','Find your own rhythm.'],
['satisfy','v. 使满意','The meal satisfied everyone.'],
['schedule','n. 日程','Check the train schedule.'],
['shelter','n. 遮蔽处','We found shelter from the rain.'],
['silent','adj. 寂静的','The house is silent at night.'],
['similar','adj. 相似的','These two words look similar.'],
['simple','adj. 简单的','Start with a simple question.'],
['solve','v. 解决','We can solve this problem together.'],
['station','n. 车站','The station is around the corner.'],
['steady','adj. 稳定的','Keep a steady pace.'],
['succeed','v. 成功','Keep trying and you will succeed.'],
['support','v. 支持','My friends support my decision.'],
['surround','v. 围绕','Trees surround the little house.'],
['temporary','adj. 暂时的','This is a temporary change.'],
['thought','n. 想法','A happy thought made her smile.'],
['tiny','adj. 极小的','There is a tiny flower by the road.'],
['travel','v. 旅行','I want to travel by train.'],
['treasure','n. 珍宝','This book is a treasure.'],
['unique','adj. 独特的','Every person is unique.'],
['unless','conj. 除非','We will walk unless it rains.'],
['useful','adj. 有用的','This map is useful.'],
['valuable','adj. 宝贵的','Your time is valuable.'],
['variety','n. 多样性','The shop offers a variety of books.'],
['wander','v. 漫步','Wander through the quiet streets.'],
['warmth','n. 温暖','I felt the warmth of the sun.'],
['wonder','v. 想知道','I wonder what happens next.'],
['youth','n. 青春','She remembers the days of her youth.'],
['zone','n. 区域','This is a quiet zone.'],
];
const EXAMPLES = {
  absorb: 'Plants absorb water from the soil.', accept: 'Please accept this small gift.',
  accompany: 'Will you accompany me to the station?', achieve: 'Small steps help you achieve your goal.',
  adapt: 'It takes time to adapt to a new city.', admire: 'I admire your patience.',
  adventure: 'Tonight is the start of an adventure.', afford: 'I can afford a cup of coffee.',
  approach: 'We approach the station slowly.', arrange: 'Arrange the books on the shelf.',
  atmosphere: 'The cafe has a warm atmosphere.', avoid: 'Try to avoid the busy road.',
  balance: 'Find a balance between work and rest.', benefit: 'Walking has many benefits.',
  brave: 'Be brave and try again.', breeze: 'A cool breeze touches my face.',
  calm: 'Stay calm and take a deep breath.', collect: 'Collect happy memories along the way.',
  comfort: 'A warm meal brings comfort.', compare: 'Compare these two pictures.',
  confident: 'Practice makes me feel confident.', convenient: 'The shop is in a convenient location.',
  curious: 'I am curious about the world.', dawn: 'We watched the sky at dawn.',
  describe: 'Describe your favorite place.', discover: 'Discover something new every day.',
};
const base = parse(RAW);
const inBank = new Set(base.map(e => e.w));
const extra = MORE.map(([w, zh, example]) => ({ w, zh, example })).filter(e => !inBank.has(e.w));
const LIST = shuffle([...base, ...extra]);
for (const e of LIST) if (EXAMPLES[e.w]) e.example = EXAMPLES[e.w];
const WARM = parse(['aim|n. 目标', 'task|n. 任务', 'goal|n. 目标', 'note|n. 笔记', 'map|n. 地图', 'mind|n. 头脑', 'road|n. 道路', 'time|n. 时间']);
G.words = { LIST, WARM, banks: { cet4: LIST } };
})();
